//! Typed kernel modules using cuda-core types.
//!
//! Each `#[cuda_module]` block in kernel-lib generates a `LoadedModule` struct
//! with typed launch methods. New async pipeline code allocates with
//! `DeviceBuffer` and dispatches directly — no conversion needed.

use std::sync::Arc;
use cuda_core::{CudaContext, CudaModule};

/// Loaded kernel modules from the cubin. Each field is a typed module
/// generated by `#[cuda_module]` — call methods directly:
///
/// ```ignore
/// modules.int4.int4_gemm_v3_ksplit_sm(&stream, config, &mut ps, &w, &s, &z, &input, n, k, gs, t, ks)?;
/// ```
pub struct KernelModules {
    pub common: infers_kernel_lib::common_kernels::common::LoadedModule,
    pub norm: infers_kernel_lib::norm_kernels::norm::LoadedModule,
    pub activation: infers_kernel_lib::activation_kernels::activation::LoadedModule,
    pub attention: infers_kernel_lib::attention_kernels::attention::LoadedModule,
    pub gdn: infers_kernel_lib::gdn_kernels::gdn::LoadedModule,
    pub int4: infers_kernel_lib::int4_kernels::int4::LoadedModule,
    pub nvfp4: infers_kernel_lib::nvfp4_kernels::nvfp4::LoadedModule,
    pub fp8: infers_kernel_lib::fp8_kernels::fp8::LoadedModule,
    pub bf16: infers_kernel_lib::bf16_kernels::bf16::LoadedModule,
}

impl KernelModules {
    /// Load all kernel modules from a cubin file.
    pub fn new(ctx: &Arc<CudaContext>, cubin_path: &str) -> anyhow::Result<Self> {
        let module = ctx.load_module_from_file(cubin_path)
            .map_err(|e| anyhow::anyhow!("Failed to load cubin {}: {:?}", cubin_path, e))?;

        Self::from_module(module)
    }

    /// Construct from an already-loaded CudaModule (avoids loading the cubin twice).
    pub fn from_module(module: Arc<CudaModule>) -> anyhow::Result<Self> {
        Ok(Self {
            common: infers_kernel_lib::common_kernels::common::from_module(module.clone())?,
            norm: infers_kernel_lib::norm_kernels::norm::from_module(module.clone())?,
            activation: infers_kernel_lib::activation_kernels::activation::from_module(module.clone())?,
            attention: infers_kernel_lib::attention_kernels::attention::from_module(module.clone())?,
            gdn: infers_kernel_lib::gdn_kernels::gdn::from_module(module.clone())?,
            int4: infers_kernel_lib::int4_kernels::int4::from_module(module.clone())?,
            nvfp4: infers_kernel_lib::nvfp4_kernels::nvfp4::from_module(module.clone())?,
            fp8: infers_kernel_lib::fp8_kernels::fp8::from_module(module.clone())?,
            bf16: infers_kernel_lib::bf16_kernels::bf16::from_module(module)?,
        })
    }
}
